version: '23.0.1'

services:
  app: 
    image: app:latest
    build: .
    ports:
     - "19000:19000"
     - "19006:19006"
  environement:
    - NODE_ENV=dev
    - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0
    - REACT_NATIVE_PACKAGER_HOSTNAME=86.220.32.178
  volumes: 
    - ./:/app/
